docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - Installation: installation.md
    - "CSRF Guards": guard.md
    - "CSRF Middleware": middleware.md
site_name: mezzio-csrf
site_description: 'CSRF protection for PSR-7 applications using mezzio-session'
repo_url: 'https://github.com/mezzio/mezzio-csrf'
extra:
    project: Mezzio
    installation:
        config_provider_class: 'Mezzio\Csrf\ConfigProvider'